import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid
} from 'drizzle-orm/pg-core';

// Loaded by drizzle-kit outside Next.js, so this file must not import server-only or '@/' paths.

export const WORKFLOW_RUN_STATUSES = ['queued', 'running', 'succeeded', 'failed'] as const;
export const workflowRunStatus = pgEnum('workflow_run_status', WORKFLOW_RUN_STATUSES);

const timestamptz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

export const workflowRuns = pgTable(
  'workflow_runs',
  {
    // UUIDv7 generated by the application; this is the run_id sent to n8n.
    id: uuid('id').primaryKey(),
    contract: text('contract').notNull(),
    status: workflowRunStatus('status').notNull().default('queued'),
    // Sanitized summary of the dispatched request: never the callback token or full listing.
    request: jsonb('request').notNull(),
    // Transitional: validated versions, models, and result until domain tables exist.
    result: jsonb('result'),
    errorCode: text('error_code'),
    errorStage: text('error_stage'),
    errorMessage: text('error_message'),
    retryable: boolean('retryable'),
    callbackTokenHash: text('callback_token_hash').notNull(),
    n8nExecutionRef: text('n8n_execution_ref'),
    attempt: integer('attempt').notNull().default(1),
    retryOfRunId: uuid('retry_of_run_id'),
    requestedAt: timestamptz('requested_at').notNull(),
    dispatchedAt: timestamptz('dispatched_at'),
    finishedAt: timestamptz('finished_at'),
    deadlineAt: timestamptz('deadline_at').notNull()
  },
  (table) => [
    foreignKey({
      name: 'workflow_runs_retry_of_run_id_fk',
      columns: [table.retryOfRunId],
      foreignColumns: [table.id]
    }),
    uniqueIndex('workflow_runs_retry_of_run_id_unique').on(table.retryOfRunId),
    index('workflow_runs_requested_at_idx').on(table.requestedAt),
    check(
      'workflow_runs_contract_check',
      sql`${table.contract} in ('ujh.analyze.v1', 'ujh.generate_proposal.v1')`
    ),
    check(
      'workflow_runs_callback_token_hash_check',
      sql`${table.callbackTokenHash} ~ '^[0-9a-f]{64}$'`
    ),
    check('workflow_runs_deadline_check', sql`${table.deadlineAt} > ${table.requestedAt}`),
    check(
      'workflow_runs_attempt_check',
      sql`${table.attempt} >= 1 and (${table.attempt} = 1) = (${table.retryOfRunId} is null)`
    ),
    check(
      'workflow_runs_error_code_check',
      sql`${table.errorCode} is null or ${table.errorCode} in ('INVALID_INPUT', 'UPSTREAM_UNAVAILABLE', 'MODEL_ERROR', 'MODEL_OUTPUT_INVALID', 'TIMEOUT', 'INTERNAL')`
    ),
    check(
      'workflow_runs_outcome_check',
      sql`case ${table.status}
        when 'succeeded' then ${table.finishedAt} is not null and ${table.result} is not null and ${table.errorCode} is null
        when 'failed' then ${table.finishedAt} is not null and ${table.result} is null and ${table.errorCode} is not null and ${table.errorMessage} is not null and ${table.retryable} is not null
        else ${table.finishedAt} is null and ${table.result} is null and ${table.errorCode} is null
      end`
    )
  ]
);

export type WorkflowRunRow = typeof workflowRuns.$inferSelect;
export type NewWorkflowRunRow = typeof workflowRuns.$inferInsert;
